### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by 3ChiThai** [MrHeroBots/musicBot#3]
When I use the command (prefix)play bot adds to the queue "Play Doh Ice cream cupcakes playset playdough by Unboxingsurpriseegg".
It does not matter what text I'll write after the command.
For example:
?play rick roll
?play Rick Astley - Never Gonna Give You Up
?play 123 
?play human music
And the bot in all cases adds "Play Doh Ice cream cupcakes playset playdough by Unboxingsurpriseegg".
Yesterday, the bot added another video all day. It was also one of the tops on YouTube.
What could be wrong? I added my youtube API to the config.js.

**Comment by 3ChiThai** [comment]
(16:44) [Nickname#0000] - success - ?play human music
{ Error: Forbidden
    at Request.callback (C:\Program Files\bot\node_modules\superagent\lib\node\index.js:675:11)
    at C:\Program Files\bot\node_modules\superagent\lib\node\index.js:883:18
    at Stream.<anonymous> (C:\Program Files\bot\node_modules\superagent\lib\node\parsers\json.js:16:7)
    at emitNone (events.js:105:13)
    at Stream.emit (events.js:207:7)
    at Unzip.<anonymous> (C:\Program Files\bot\node_modules\superagent\lib\node\unzip.js:53:12)
    at emitNone (events.js:110:20)
    at Unzip.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
  status: 403,
  response:
   Response {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     res:
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 403,
        statusMessage: 'FORBIDDEN',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Object],
        setEncoding: [Function],
        on: [Function],
        text: '{"code": 50013, "message": "Missing Permissions"}',
        read: [Function] },
     request:
      Request {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _agent: false,
        _formData: null,
        method: 'DELETE',
        url: 'https://discordapp.com/api/v6/channels/348098890467115008/messages/349111392592461824',
        _header: [Object],
        header: [Object],
        writable: true,
        _redirects: 0,
        _maxRedirects: 5,
        cookies: '',
        qs: {},
        qsRaw: [],
        _redirectList: [],
        _streamRequest: false,
        req: [Object],
        protocol: 'https:',
        host: 'discordapp.com',
        _endCalled: true,
        _callback: [Function],
        res: [Object],
        response: [Circular],
        called: true },
     req:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: false,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'DELETE /api/v6/channels/348098890467115008/messages/349111392592461824 HTTP/1.1\r\nHost: discordapp.com\r\nAccept-Encoding: gzip, deflate\r\nUser-Agent: DiscordBot (https://github.com/hydrabolt/discord.js, 11.0.0)\r\nauthorization: Bot MzQ4NDA3Mjc3ODAxMzA4MTYw.DHmgPw.PBo98srCP2ZMnW7FYqPqEZgCSmE\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'DELETE',
        path: '/api/v6/channels/348098890467115008/messages/349111392592461824',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     text: '{"code": 50013, "message": "Missing Permissions"}',
     body: { code: 50013, message: 'Missing Permissions' },
     files: undefined,
     buffered: true,
     headers:
      { date: 'Mon, 21 Aug 2017 08:44:07 GMT',
        'content-type': 'application/json',
        'transfer-encoding': 'chunked',
        connection: 'close',
        'set-cookie': [Array],
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        via: '1.1 google',
        'alt-svc': 'clear',
        server: 'cloudflare-nginx',
        'cf-ray': '391c4f02e86c4e72-DME',
        'content-encoding': 'gzip' },
     header:
      { date: 'Mon, 21 Aug 2017 08:44:07 GMT',
        'content-type': 'application/json',
        'transfer-encoding': 'chunked',
        connection: 'close',
        'set-cookie': [Array],
        'strict-transport-security': 'max-age=31536000; includeSubDomains',
        via: '1.1 google',
        'alt-svc': 'clear',
        server: 'cloudflare-nginx',
        'cf-ray': '391c4f02e86c4e72-DME',
        'content-encoding': 'gzip' },
     statusCode: 403,
     status: 403,
     statusType: 4,
     info: false,
     ok: false,
     redirect: false,
     clientError: true,
     serverError: false,
     error:
      { Error: cannot DELETE /api/v6/channels/348098890467115008/messages/349111392592461824 (403)
          at Response.toError (C:\Program Files\bot\node_modules\superagent\lib\node\response.js:94:13)
          at ResponseBase._setStatusProperties (C:\Program Files\bot\node_modules\superagent\lib\response-base.js:122:16)
          at new Response (C:\Program Files\bot\node_modules\superagent\lib\node\response.js:40:8)
          at Request._emitResponse (C:\Program Files\bot\node_modules\superagent\lib\node\index.js:738:20)
          at C:\Program Files\bot\node_modules\superagent\lib\node\index.js:883:38
          at Stream.<anonymous> (C:\Program Files\bot\node_modules\superagent\lib\node\parsers\json.js:16:7)
          at emitNone (events.js:105:13)
          at Stream.emit (events.js:207:7)
          at Unzip.<anonymous> (C:\Program Files\bot\node_modules\superagent\lib\node\unzip.js:53:12)
          at emitNone (events.js:110:20)
        status: 403,
        text: '{"code": 50013, "message": "Missing Permissions"}',
        method: 'DELETE',
        path: '/api/v6/channels/348098890467115008/messages/349111392592461824' },
     accepted: false,
     noContent: false,
     badRequest: false,
     unauthorized: false,
     notAcceptable: false,
     forbidden: true,
     notFound: false,
     type: 'application/json',
     links: {},
     setEncoding: [Function: bound ],
     redirects: [] } }

**Comment by Heroj04** [comment]
This has been fixed in commit dbd03dc
Which is a part of the development branch.
I have stopped working on the current version of this bot and am now working on the rewrite for v2.0.0
If you would like you can switch to the development branch or the v2 branch to test out fixes and new features.

In regards to that error message, I'm seeing a lot of 'unauthorised' in it, be sure the bot has permission to join all channels and send messages in all channels. It should also be able to delete messages as it will try to delete the message which invoked a command (i.e., Your message) (This seems to be the actual problem, can't delete users messages)
